  max_height: 0.35
  min_height: 0.1
  max_range: 20.0
  min_range: 0.5
  min_angle: -2.0944
  max_angle: 2.0944
  ransac_thre: 0.1
  plane_dis_thre: 0.2
  voxel_filter_flag: false
  voxel_filter_size: 0.05
  radius_filter_flag: false
  radius_filter_r: 0.3
  radius_filter_num: 10
  angle_tan_value: 1.732
  use_polygon: true
  point2image_size: 0.02
  segmentation_config_file: "segmentation/segmentation_app.yaml"
  fusion_lidar_cam_odom_config_file: "obstacle_detection/fusion_lidar_cam_odom_app.yaml"
  state_machine_config_file: "state_config/obstacle_detection_state_machine.txt"
  calib_file: "/ota/calibration_results.yaml"
  # 1920->960
  camera_intrinsics_scale_x: 0.5
  # 1080->544
  camera_intrinsics_scale_y: 0.5037037037037037
